# Generated by Django 5.0.4 on 2024-04-10 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='genero',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Livros',
        ),
    ]
