# Generated by Django 5.0.4 on 2024-04-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0003_initial'),
        ('livros', '0006_remove_livros_genero_livros_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livroemprestimo',
            name='genero',
        ),
        migrations.AddField(
            model_name='livroemprestimo',
            name='genero',
            field=models.ManyToManyField(to='livros.genero'),
        ),
    ]
