# Generated by Django 5.0.4 on 2024-04-21 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0004_remove_livroemprestimo_genero_livroemprestimo_genero'),
        ('leitores', '0002_leitor_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='leitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leitores.leitor'),
        ),
    ]
