# Generated by Django 5.0.4 on 2024-04-21 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0005_alter_emprestimo_leitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livroemprestimo',
            name='genero',
        ),
    ]
