# Generated by Django 5.0.4 on 2024-04-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0006_remove_livroemprestimo_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_final',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_inicial',
            field=models.DateField(),
        ),
    ]
