# Generated by Django 5.0.4 on 2024-04-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0007_alter_emprestimo_data_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livroemprestimo',
            name='imagem',
            field=models.CharField(default=None, max_length=1200, null=True),
        ),
    ]
