# Generated by Django 5.0.4 on 2024-04-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livros_estoque_livros_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='sinopse',
            field=models.TextField(blank=True, max_length=1200, null=True),
        ),
    ]
