# Generated by Django 5.0.4 on 2024-04-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_rename_sinopse_livros_sinopse_curta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='sinopse_longa',
            field=models.TextField(blank=True, max_length=12000, null=True),
        ),
    ]
