# Generated by Django 5.0.4 on 2024-04-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_alter_livros_sinopse_longa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='genero',
        ),
        migrations.AddField(
            model_name='livros',
            name='genero',
            field=models.ManyToManyField(to='livros.genero'),
        ),
    ]
